version: "3.8"

services:

  mariadb: 
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: user-data
      MYSQL_USER: cinematch
      MYSQL_PASSWORD: cinematchpw
    ports: 
      - 3306:3306 

  mongo-db:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db

  discovery-server:
    image: mschippers/cinematch-discovery-server:main
    ports:
      - ${EUREKA_PORT:-8761}:8761

  api-gateway:
    image: mschippers/cinematch-api-gateway:main
    ports:
      - ${GATEWAY_PORT:-8080}:8080
    environment:
      - SERVICE_URL_DEFAULT_ZONE=http://discovery-server:8761/eureka
  
  user-data-service:
    image: mschippers/cinematch-user-data-service:main
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/user-data
      - SPRING_DATASOURCE_USERNAME=cinematch
      - SPRING_DATASOURCE_PASSWORD=cinematchpw
      - SPRING_DATASOURCE_ROOT_PASSWORD=admin
      - SERVICE_URL_DEFAULT_ZONE=http://discovery-server:8761/eureka

  user-preferences-service:
    image: mschippers/cinematch-user-preferences-service:main
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo-db/user-preferences
      - SERVICE_URL_DEFAULT_ZONE=http://discovery-server:8761/eureka

  user-matching-service:
    image: mschippers/cinematch-user-matching-service:main
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo-db/user-matching
      - SERVICE_URL_DEFAULT_ZONE=http://discovery-server:8761/eureka

volumes:
  mariadb-data:
  mongodb-data: